### ISSUE TITLE
lintのciを作る

### ISSUE THREAD

**Issue by takuma-shiraki** [op-tennis/Practice-Backend#5]
## 背景
node.jsのtestのciを作れたので、次はlintのciを作る

## 対応内容

1. ts用のlintパッケージの選定
2. yamlの作成
3. 実行＆ciが成功する確認

**Comment by takuma-shiraki** [comment]
## ts用のlintパッケージの選定
Action作成の検索窓に「ts lint」で検索する
スターが多いのは、下記の二つ

- https://github.com/marketplace/actions/eslint-js-ts-action
  - スター:25

- https://github.com/marketplace/actions/tslint-checks
  - スター:34

**Comment by takuma-shiraki** [comment]
## yamlの作成

Installationに下記のyamlが記載されている。
既存のyamlにこれを追加すれば実行できるよということみたい
一旦、testとlintは別にしておきたいので、別のファイルに記載する

手順

- 既存のyamlをコピー
- 下記のyamlをコピー


```yaml
            - name: TSLint checks
  # You may pin to the exact commit or the version.
  # uses: mooyoul/tslint-actions@bb86bb5a3b355c1a6762e1a05949aace76e14ec5
  uses: mooyoul/tslint-actions@v1.1.1
  with:
    # Github Token
    token: 
    # Path of TypeScript Project file
    project: # optional
    # Path of TSLint configuration
    config: # optional, default is tslint.json
    # Glob pattern to match
    pattern: # optional
          
```

**Comment by takuma-shiraki** [comment]
node_moduleのバージョンが`21.7.0`以上になっていないらしい。
node-version:のcache: 'npm'を追加する[212ad4f](https://github.com/op-tennis/Practice-Backend/commit/212ad4f28f85ef1b0af7c06fdfbdb52e887853a9)

```sh
Run npm ci
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: app@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: app@1.0.0
npm ERR! notsup Required: {"node":">=21.7.0"}
npm ERR! notsup Actual:   {"npm":"10.5.2","node":"v20.13.1"}
```

**Comment by takuma-shiraki** [comment]
次は、lintでエラー
npm lintというコマンドが見つからんらしい

```sh
Run npm lint
Unknown command: "lint"

Did you mean this?
    npm link # Symlink a package folder

To see a list of supported npm commands, run:
  npm help
Error: Process completed with exit code 1.
```

**Comment by takuma-shiraki** [comment]
[reviewdog/action-eslint](https://github.com/reviewdog/action-eslint)のREADMEに下記の記述あった

> This action runs [eslint](https://github.com/eslint/eslint) with [reviewdog](https://github.com/reviewdog/reviewdog) on pull requests to improve code review experience.

このアクションはeslintとreviewdogをプルリクエストに対して実行し、コードレビューの経験を向上させます。

[eslint/eslint](https://github.com/eslint/eslint)を経由してlintを実行しているらいい？
eslint/eslintをインストールしてないので、インストールする。
でも、これはeslintでlintしているのかreviewdogでlintしてるのかわかるのか？

参考記事には下記のようなことが書いてあった。これ、reviewdog必要なくね？？
[見ての通り、上記の設定は処理として冗長です。 ESLint を reviewdog 経由で1回、直接実行で1回の計2回実行しています。](https://tech.actindi.net/2019/10/11/090521#:~:text=%E8%A6%8B%E3%81%A6%E3%81%AE%E9%80%9A%E3%82%8A%E3%80%81%E4%B8%8A%E8%A8%98%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%AF%E5%87%A6%E7%90%86%E3%81%A8%E3%81%97%E3%81%A6%E5%86%97%E9%95%B7%E3%81%A7%E3%81%99%E3%80%82%20ESLint%20%E3%82%92%20reviewdog%20%E7%B5%8C%E7%94%B1%E3%81%A71%E5%9B%9E%E3%80%81%E7%9B%B4%E6%8E%A5%E5%AE%9F%E8%A1%8C%E3%81%A71%E5%9B%9E%E3%81%AE%E8%A8%882%E5%9B%9E%E5%AE%9F%E8%A1%8C%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82)

**Comment by takuma-shiraki** [comment]
## Flat Configシステムで記載する

```yml
export default {
    languageOptions: {
        ecmaVersion: 12,
        sourceType: 'module',
        globals: {
            Atomics: 'readonly',
            SharedArrayBuffer: 'readonly',
            __dirname: 'readonly',
            console: 'readonly',
            module: 'readonly',
            exports: 'readonly',
            require: 'readonly',
            process: 'readonly',
            Buffer: 'readonly',
            global: 'readonly',
            // 他のグローバル変数もここに追加できます
        },
    },
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    parser: '@typescript-eslint/parser',
    plugins: [
        '@typescript-eslint',
    ],
    rules: {
      // ここに独自のルールを追加
    },
};
```

`npx eslint './**/*.{ts,js}'`を実行したら下記のエラーが出た。
```sh
(node:94805) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

Oops! Something went wrong! :(

ESLint: 8.57.0

/Users/opm006712/git/github.com/op-tennis/Practice-Backend/eslint.config.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1279:20)
    at Module._compile (node:internal/modules/cjs/loader:1331:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
```
